"""add users.password_hash

Revision ID: 2fe660361238
Revises: a050622bac2d
Create Date: 2026-06-23 17:10:49.381573
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fe660361238'
down_revision: Union[str, None] = 'a050622bac2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
