"""initial schema

Revision ID: a050622bac2d
Revises: 
Create Date: 2026-06-23 16:49:11.237672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a050622bac2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Enum('classification', 'extraction', 'due_date_resolution', 'vision_analysis', 'document_analysis', 'evaluation', name='ai_run_type'), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_input_hash', 'ai_runs', ['input_hash'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.Enum('telegram', 'slack', 'email', 'whatsapp', 'discord', name='connector_type'), nullable=False),
    sa.Column('external_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_type', 'external_chat_id', name='uq_chats_connector_external')
    )
    op.create_table('connector_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_type', sa.Enum('telegram', 'slack', 'email', 'whatsapp', 'discord', name='connector_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Enum('pass', 'fail', 'partial', 'pending', name='evaluation_result'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'assignee', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_assignees_user')
    )
    op.create_index('ix_assignees_telegram_user_id', 'assignees', ['telegram_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('sync_started', 'sync_finished', 'candidate_created', 'candidate_edited', 'candidate_approved', 'candidate_rejected', 'work_item_status_changed', 'assignee_created', 'assignee_updated', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.Enum('candidate', 'work_item', 'assignee', 'chat', 'sync_run', 'message', name='audit_entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_type', sa.Enum('task', 'request', 'reminder', 'idea', 'knowledge', 'decision', 'risk', name='candidate_type'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('new', 'needs_review', 'edited', 'approved', 'rejected', 'duplicate', 'error', name='candidate_status'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('task_confidence', sa.Float(), nullable=True),
    sa.Column('context_confidence', sa.Float(), nullable=True),
    sa.Column('assignee_confidence', sa.Float(), nullable=True),
    sa.Column('priority_confidence', sa.Float(), nullable=True),
    sa.Column('due_date_confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidates_status', 'candidates', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('external_message_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_external_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('sender_display_name', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'voice', 'image', 'document', 'mixed', name='message_type'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Enum('new', 'normalized', 'analyzed', 'failed', 'skipped', name='message_processing_status'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'external_message_id', name='uq_messages_chat_external')
    )
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_external_message_id', 'messages', ['external_message_id'], unique=False)
    op.create_index('ix_messages_processing_status', 'messages', ['processing_status'], unique=False)
    op.create_index('ix_messages_sent_at', 'messages', ['sent_at'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('scheduled', 'manual', 'retry', name='sync_trigger_type'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial_success', 'failed', name='sync_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_read', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('messages_saved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('messages_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('candidates_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_external_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', name='uq_sync_states_chat')
    )
    op.create_table('candidate_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['assignees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'assignee_id', name='uq_candidate_assignees_pair')
    )
    op.create_index('ix_candidate_assignees_candidate_id', 'candidate_assignees', ['candidate_id'], unique=False)
    op.create_table('candidate_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'label_id', name='uq_candidate_labels_pair')
    )
    op.create_table('candidate_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'context', 'supporting', name='candidate_message_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'message_id', name='uq_candidate_messages_pair')
    )
    op.create_index('ix_candidate_messages_candidate_id', 'candidate_messages', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_messages_message_id', 'candidate_messages', ['message_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.Enum('voice', 'image', 'document', name='attachment_type'), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('new', 'processing', 'processed', 'failed', 'skipped', name='attachment_processing_status'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_candidate_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('task', 'request', 'reminder', 'idea', 'knowledge', name='work_item_type'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('inbox', 'backlog', 'ready', 'in_progress', 'blocked', 'review', 'done', 'cancelled', 'archived', name='work_item_status'), server_default=sa.text("'inbox'"), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_candidate_id', name='uq_work_items_source_candidate')
    )
    op.create_index('ix_work_items_status', 'work_items', ['status'], unique=False)
    op.create_table('work_item_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['assignees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'assignee_id', name='uq_work_item_assignees_pair')
    )
    op.create_index('ix_work_item_assignees_assignee_id', 'work_item_assignees', ['assignee_id'], unique=False)
    op.create_table('work_item_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'label_id', name='uq_work_item_labels_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_item_labels')
    op.drop_index('ix_work_item_assignees_assignee_id', table_name='work_item_assignees')
    op.drop_table('work_item_assignees')
    op.drop_index('ix_work_items_status', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index('ix_message_attachments_message_id', table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_candidate_messages_message_id', table_name='candidate_messages')
    op.drop_index('ix_candidate_messages_candidate_id', table_name='candidate_messages')
    op.drop_table('candidate_messages')
    op.drop_table('candidate_labels')
    op.drop_index('ix_candidate_assignees_candidate_id', table_name='candidate_assignees')
    op.drop_table('candidate_assignees')
    op.drop_table('sync_states')
    op.drop_table('sync_runs')
    op.drop_index('ix_messages_sent_at', table_name='messages')
    op.drop_index('ix_messages_processing_status', table_name='messages')
    op.drop_index('ix_messages_external_message_id', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_candidates_status', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_assignees_telegram_user_id', table_name='assignees')
    op.drop_table('assignees')
    op.drop_table('users')
    op.drop_table('labels')
    op.drop_table('evaluation_cases')
    op.drop_table('connector_accounts')
    op.drop_table('chats')
    op.drop_index('ix_ai_runs_input_hash', table_name='ai_runs')
    op.drop_table('ai_runs')
    # Drop native enum types — Alembic autogenerate does not, which would break a re-upgrade
    # (CREATE TYPE on an existing type). Listed explicitly so downgrade fully reverses upgrade.
    for _enum in (
        "user_role", "connector_type", "message_type", "message_processing_status",
        "attachment_type", "attachment_processing_status", "sync_trigger_type", "sync_run_status",
        "candidate_type", "candidate_status", "priority", "candidate_message_role",
        "work_item_type", "work_item_status", "ai_run_type", "evaluation_result",
        "audit_action", "audit_entity_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
    # ### end Alembic commands ###
